FROM nginx:stable-alpine
MAINTAINER Thomas Vollstädt <vollstaedt@ofigo.de>

COPY dist/prod/ /opt/app/dist/prod/
COPY .docker/nginx.conf /etc/nginx/template.conf

ENV NGINX_HOST ${NGINX_HOST:-localhost}
ENV NGINX_PORT ${NGINX_PORT:-80}

CMD envsubst '$NGINX_HOST $NGINX_PORT' < /etc/nginx/template.conf > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"
